[package]
name = "evcxr"
version = "0.14.2"
license = "MIT OR Apache-2.0"
description = "An Evaluation Context for Rust"
repository = "https://github.com/evcxr/evcxr"
readme = "README.md"
authors = ["The Evcxr Authors"]
edition = "20