# Trigger a release when a tag is pushed that starts with v then some number.
on:
  push:
    tags:
      - 'v[0-9]+.*'

name: Release

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write # Needed for creating releases

    strategy:
      matrix:
        include:
        - build: linux
          os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
        - build: macos
          os: macos-latest
          target: x86_64-apple-darwin
        - build: windows
          os: windows-2019
          target: x86_64-pc-